#!/usr/bin/env bash

if test ! $(which brew); then
  echo "Installing homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "Updating homebrew..."
brew update

brew tap caskroom/cask

brew install mongodb 
brew cask install shiftit robomongo transmission

ln -sf ~/.dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/.dotfiles/.gitconfig ~/.gitconfig

source ~/.bash_profile
